### PR TITLE
accept Strings through MOI.RawParameter

### LINKED ISSUE #97: JuMP v0.21 Support
The following example,
```
using JuMP; using ECOS
solver = with_optimizer(ECOS.Optimizer, verbose=0)
m = Model(solver)
```
seems to result in the following error,
```
ERROR: MethodError: Cannot `convert` an object of type String to an object of type Symbol
Closest candidates are:
  convert(::Type{T}, ::GenericAffExpr{T,VarType} where VarType) where T at ~/.julia/packages/JuMP/Sp4sR/src/aff_expr.jl:318
  convert(::Type{T}, ::GenericQuadExpr{T,VarType} where VarType) where T at ~/.julia/packages/JuMP/Sp4sR/src/quad_expr.jl:329
  convert(::Type{T}, ::T) where T at essentials.jl:168
  ...
Stacktrace:
 [1] setindex!(::Dict{Symbol,Any}, ::Int64, ::String) at ./dict.jl:372
 [2] set(::ECOS.Optimizer, ::MathOptInterface.RawParameter, ::Int64) at ~/.julia/packages/ECOS/moZme/src/MOI_wrapper.jl:77
 [3] _instantiate_and_check(::MathOptInterface.OptimizerWithAttributes) at ~/.julia/packages/MathOptInterface/DmQBj/src/instantiate.jl:77
 [4] #instantiate#35(::Type{Float64}, ::Bool, ::typeof(MathOptInterface.instantiate), ::MathOptInterface.OptimizerWithAttributes) at ~/.julia/packages/MathOptInterface/DmQBj/src/instantiate.jl:107
 [5] (::MathOptInterface.var"#kw##instantiate")(::NamedTuple{(:with_bridge_type, :with_names),Tuple{DataType,Bool}}, ::typeof(MathOptInterface.instantiate), ::MathOptInterface.OptimizerWithAttributes) at ./none:0
 [6] #set_optimizer#96(::Bool, ::typeof(set_optimizer), ::Model, ::MathOptInterface.OptimizerWithAttributes) at ~/.julia/packages/JuMP/Sp4sR/src/optimizer_interface.jl:66
 [7] #Model#16 at ./none:0 [inlined]
 [8] Model(::MathOptInterface.OptimizerWithAttributes) at ~/.julia/packages/JuMP/Sp4sR/src/JuMP.jl:231
 [9] top-level scope at REPL[7]:1
```
Seems to be an issue similar to https://github.com/JuliaOpt/SCS.jl/issues/173
CC @odow @blegat @mlubin

### PR DESCRIPTION
**Pull request by mlubin**
Fixes #97 
CC @odow @blegat

### CODE REVIEW

File: test/MOI_wrapper.jl [hunk 1]
```diff
@@ -57,3 +57,14 @@ end
...
 end
+
+@testset "MOI.RawParameter" begin
+    model = ECOS.Optimizer()
+    # TODO: remove symbol cases when deprecation is removed.
+    MOI.set(model, MOI.RawParameter(:abstol), 1e-5)
+    @test MOI.get(model, MOI.RawParameter(:abstol)) ≈ 1e-5
+    @test MOI.get(model, MOI.RawParameter("abstol")) ≈ 1e-5
+    MOI.set(model, MOI.RawParameter("abstol"), 2e-5)
+    @test MOI.get(model, MOI.RawParameter(:abstol)) ≈ 2e-5
```
Comment (blegat) [inline test/MOI_wrapper.jl]: This should be double =

Comment (blegat) [reply test/MOI_wrapper.jl]: I missread the approx as a single =
